### ISSUE TITLE
KeyError while publishing a page

### ISSUE THREAD

**Issue by o-zander** [django-cms/django-cms#2111]
The copy_plugin function throws an error because the parent plugin isn't in the cache. Can't figure out why this happens. Traceback enclosed:

Traceback (most recent call last):

  File "/var/www/project/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
response = callback(request, _callback_args, *_callback_kwargs)

File "/var/www/project/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
response = view_func(request, _args, *_kwargs)

File "/var/www/project/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
response = view_func(request, _args, *_kwargs)

File "/var/www/project/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 202, in inner
return view(request, _args, *_kwargs)

File "/var/www/project/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
return func(_args, *_kwargs)

File "/var/www/project/env/local/lib/python2.7/site-packages/reversion/revisions.py", line 301, in do_revision_context
return func(_args, *_kwargs)

File "/var/www/project/env/src/django-cms/cms/admin/pageadmin.py", line 914, in publish_page
page.publish()

File "/var/www/project/env/src/django-cms/cms/models/pagemodel.py", line 433, in publish
self._copy_contents(public_page)

File "/var/www/project/env/src/django-cms/cms/models/pagemodel.py", line 210, in _copy_contents
copy_plugins_to(plugins, ph)

File "/var/www/project/env/src/django-cms/cms/utils/copy_plugins.py", line 21, in copy_plugins_to
new_plugin = old_plugin.copy_plugin(to_placeholder, plugin_language, old_parent_cache)

File "/var/www/project/env/src/django-cms/cms/models/pluginmodel.py", line 262, in copy_plugin
new_plugin.parent = parent_cache[self.parent_id]

KeyError: 3197L

**Comment by eimsbush** [comment]
We still have this error with 3.2.5 with a projects database which moved and has been migrating up since django 2.x. fix-mptt and fix-tree never solved it.

The only way we can avoid this error and use the copy methods is using a try/exept KeyError like in: https://github.com/eimsbush/django-cms/pull/1/files
