### ISSUE TITLE
'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by ghost** [django-cms/django-cms#2744]
404's will throw this error:

Internal Server Error: /xxx
Traceback (most recent call last):
  File "/virtualenvs/xxx/lib/python2.7/site-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/virtualenvs/xxx/src/django-cms/cms/middleware/toolbar.py", line 88, in process_response
    if request.user.is_staff:
AttributeError: 'WSGIRequest' object has no attribute 'user'

**Comment by adityababar07** [comment]
Environment:


Request Method: GET
Request URL: http://localhost:8000/profile/hacker07/

Django Version: 3.0
Python Version: 3.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles',
 'blog.apps.BlogConfig',
 'accounts.apps.AccountsConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/hacker07/.local/share/virtualenvs/blog-2-Wg3YqIyx/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/hacker07/.local/share/virtualenvs/blog-2-Wg3YqIyx/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hacker07/.local/share/virtualenvs/blog-2-Wg3YqIyx/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hacker07/.local/share/virtualenvs/blog-2-Wg3YqIyx/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hacker07/.local/share/virtualenvs/blog-2-Wg3YqIyx/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/hacker07/.local/share/virtualenvs/blog-2-Wg3YqIyx/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 106, in dispatch
    user_test_result = self.get_test_func()()
  File "/home/hacker07/blog-2/accounts/views.py", line 25, in test_func
    return obj.username == self.request.customuser

Exception Type: AttributeError at /profile/hacker07/
Exception Value: 'WSGIRequest' object has no attribute 'customuser'


thanks in advance

**Comment by jrief** [comment]
Please don't just paste same stack-trace without any further description. The error occurs outside of django-CMS's code, so check there.

**Comment by adityababar07** [comment]
ok
