### ISSUE TITLE
cms.tests.toolbar.ToolbarMiddlewareTest.test_app_setted_show_toolbar_in_cms_urls doesn't actually use nonroot urls

### ISSUE THREAD

**Issue by ojii** [django-cms/django-cms#4289]
Running `cms.tests.toolbar.ToolbarMiddlewareTest.test_app_setted_show_toolbar_in_cms_urls` isolated fails with:

```
======================================================================
ERROR: test_app_setted_show_toolbar_in_cms_urls (cms.tests.toolbar.ToolbarMiddlewareTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/test/utils.py", line 196, in inner
    return test_func(*args, **kwargs)
  File "/home/jonas/tmp/django-cms/cms/tests/toolbar.py", line 120, in test_app_setted_show_toolbar_in_cms_urls
    request = self.get_page_request(page, self.get_anon())
  File "/home/jonas/tmp/django-cms/cms/tests/toolbar.py", line 43, in get_page_request
    path = path or page and page.get_absolute_url()
  File "/home/jonas/tmp/django-cms/cms/models/pagemodel.py", line 161, in get_absolute_url
    return reverse('pages-root')
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 433, in _reverse_with_prefix
    self._populate()
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 285, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jonas/tmp/django-cms/cms/test_utils/project/nonroot_urls.py", line 18, in <module>
    url(r'^content/', include('cms.urls', app_name=get_cms_setting('APP_NAME'))),
  File "/home/jonas/tmp/django-cms/env/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 21, in include
    raise ValueError('Must specify a namespace if specifying app_name.')
ValueError: Must specify a namespace if specifying app_name.
```

When running non-isolated, it uses the normal urls because simply overriding `ROOT_URLCONF` does nothing.

**Comment by FinalAngel** [comment]
@yakky any idea when we could fix this?

**Comment by Aiky30** [comment]
Hello @ojii,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
