### ISSUE TITLE
Rare restore_sekizai_context error

### ISSUE THREAD

**Issue by doctormo** [django-cms/django-cms#5021]
Every so often, maybe when the webserver is stressed, we get this error concerning the cms_tags module:

```
Internal Server Error: /en/download/linux/
Traceback (most recent call last):
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/classytags/core.py", line 146, in render
    return self.render_tag(context, **kwargs)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 83, in render_tag
    rendered_contents = nodelist.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/classytags/core.py", line 146, in render
    return self.render_tag(context, **kwargs)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 83, in render_tag
    rendered_contents = nodelist.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/classytags/core.py", line 146, in render
    return self.render_tag(context, **kwargs)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/cms/templatetags/cms_tags.py", line 672, in render_tag
    rendered_contents = nodelist.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/classytags/core.py", line 146, in render
    return self.render_tag(context, **kwargs)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/cms/templatetags/cms_tags.py", line 301, in render_tag
    content = get_placeholder_content(context, request, page, name, inherit, nodelist)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/cms/templatetags/cms_tags.py", line 220, in get_placeholder_content
    placeholder = _get_placeholder(current_page, page, context, name)
  File "/var/www/www.inkscape.org/pythonenv/lib/python2.7/site-packages/cms/templatetags/cms_tags.py", line 193, in _get_placeholder
    restore_sekizai_context(context, cached_value['sekizai'])
TypeError: list indices must be integers, not str
```

**Comment by evildmp** [comment]
@ojii Can you comment?

**Comment by ojii** [comment]
So `cms.cache.placeholder.get_placeholder_cache` returns a list, but it should return a dictionary (or `None`). The value is set via `cms.cache.placeholder.set_placeholder_cache` in https://github.com/divio/django-cms/blob/052f51691804a0882b0e436aad40d9c0e95ce181/cms/plugin_rendering.py#L185, where it's clearly a dictionary. Not sure why it would turn into a list.

@doctormo what is your cache backend?

**Comment by doctormo** [comment]
memcached running on localhost.

**Comment by ktosiek** [comment]
I'm also seeing this, plus similar mismatch in _get_placeholder_cache_version. The second one gets a `5` for key `cms-|placeholder_cache_version|id:589|lang:pl|site:2`, while it expects an iterable of (version, vary_on_list). I'm also using memcached.

**Comment by ktosiek** [comment]
This looks similar: http://stackoverflow.com/a/24082360
I could recreate the issue by running `ab -t 5 -c 20` against my site.
I'm running on uWSGI, and adding `close-on-exec = true` seems to help - I couldn't replicate after adding that option.

**Comment by ktosiek** [comment]
Update: nope, it has still happened over the weekend with `close-on-exec = true`
