### ISSUE TITLE
PageExtension/TitleExtension.public_extension sometimes loses it's reference

### ISSUE THREAD

**Issue by vstoykov** [django-cms/django-cms#5718]
Django 1.8.14
Django CMS 3.3.2

This is probably similar to #4940 but is related to page/title extensions instead of the pages/titles.

I have disabled revision functionality as mentioned in #5690 by @czpython  but still page/title extensions 's field `public_extension` breaks every day and I need to manually fix them. Sometimes it only miss from one side to another (one of the extensions knows which is the other but the other don't) and some times even none of them knows for the other. In the later case I check from the `extended_object` if it has public/draft version for the current object and if that object has extension of the same type in order to update the value correctly.

Probably this is related to something missing when copying extensions from one page to another or when publishing. I'm not sure when it happens.

When this problem occurs and given page is changed and need to be published then there are error 500 for duplicate `extended_object_id`

```
Traceback (most recent call last):
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/path/to/virtualenv/lib/python3.4/site-packages/cms/admin/pageadmin.py", line 85, in do_revision_context
    return func(*args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/cms/admin/pageadmin.py", line 1250, in publish_page
    published = page.publish(language)
  File "/path/to/virtualenv/lib/python3.4/site-packages/cms/models/pagemodel.py", line 735, in publish
    cms_signals.post_publish.send(sender=Page, instance=self, language=language)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/path/to/virtualenv/lib/python3.4/site-packages/cms/extensions/extension_pool.py", line 66, in _receiver
    self._copy_title_extensions(draft_page, None, language, clone=False)
  File "/path/to/virtualenv/lib/python3.4/site-packages/cms/extensions/extension_pool.py", line 88, in _copy_title_extensions
    instance.copy_to_public(target_title, language)
  File "/path/to/virtualenv/lib/python3.4/site-packages/cms/extensions/models.py", line 80, in copy_to_public
    this.save(mark_page=False)
  File "/path/to/virtualenv/lib/python3.4/site-packages/cms/extensions/models.py", line 123, in save
    return super(BaseExtension, self).save(*args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "pageimagesextension_extended_object_id_key"
DETAIL:  Key (extended_object_id)=(1363) already exists.
```

**Comment by vstoykov** [comment]
Now when I look closer to the code I don't see the same logic as for the pages (public to point to draft and draft to public). Only draft object is pointing to the public one. I don't know if this is intentional or not.

In this situation there is no public instance which will point to the draft but sometimes even the draft does not point to the public version. And probably then the problem occurs. I will try to continue with the investigation of this issue.

**Comment by jedie** [comment]
I ran into the same issues with Django CMS 3.4.5 ... It happens on one cms page. It's fine on other cms pages with the same page extension...

**Comment by vivazzi** [comment]
I get this bug too. Django==1.10.7, django-cms==3.5.0

I have understood the strange behavior. This bug is appear when run these steps:

1. Create an extension (or "Save" in another way from Menu / Page / My extension)
2. Publish page
3. Go to the draft version by clicking "Edit"
4. Remove extension (by going to Menu / Page / My extension and clicking "Delete")
5. Create an extension again (Menu / Page / My Extension)
6. And try to publish the page.

An bug appears in the sixth step.

My workaround solution is to delete `extended_object` if any. I override `copy_to_public()` in `MyExtension` class:

```
class MyExtension(PageExtension):
    ... # custom fields

    def copy_to_public(self, public_object, language):
        if not self.public_extension:
            try:
                self.__class__.objects.get(extended_object_id=public_object.pk).delete()
            except self.__class__.DoesNotExist:
                pass

        return super(PageExt, self).copy_to_public(public_object, language)
```

But in django cms code I don't understand how to decide this problem...
