### ISSUE TITLE
migration dajngo cms 0019 does not apply successfully on multiple database

### ISSUE THREAD

**Issue by j-san** [django-cms/django-cms#6413]
### Summary

migration dajngo cms 0019 apply on a database the does not belongs to cms.

### Expected behaviour

The migration is skipped

### Actual behaviour

When running `python manage.py migrate` the following error occurd

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python2.7/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/usr/local/lib/python2.7/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 69, in create_test_db
    run_syncdb=True,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/cms/migrations/0019_set_pagenode.py", line 68, in apply
    connection.introspection.get_table_description(connection.cursor(), 'cms_page')
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/introspection.py", line 81, in get_table_description
    cursor.execute("SELECT * FROM %s LIMIT 1" % self.connection.ops.quote_name(table_name))
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "cms_page" does not exist
LINE 1: SELECT * FROM "cms_page" LIMIT 1
                      ^
```

### Environment

* Python version:
2.7
* Django version:
1.11.13
* django CMS version:
3.5.2

db router:
```
class XxxRouter(object):
    # (...)
    def allow_migrate(self, db, app_label, model_name=None, **hints):
        if db == 'xxx_db' or app_label == 'xxx':
            return db == 'xxx_db' and app_label == 'xxx'
        return None
```

Thanks for your help !

**Comment by czpython** [comment]
Hello @j-san,
Thanks for reporting this.
The migration can't be skipped unless the router is configured to do so.
Please have a look at https://docs.djangoproject.com/en/2.0/topics/db/multi-db/#synchronizing-your-databases

You'll need to implement the `allow_migrate` method on your router and also pass in the database you want to run migrations for to the migrate command.

**Comment by j-san** [comment]
Hello @czpython,

Thank you for your response.

As mentioned in the issue report, there is a db router with the `allow_migrate` method and it's working fine for all other migrations except this one (0019 and 0020). The `allow_migrate` method is not called at all and I suspect that making queries in Migration.apply before super call (before `allow_migrate` is checked) is the root issue.

**Comment by Stahet** [comment]
+1

**Comment by renjithraj2005** [comment]
I have the same issue with Postgres and stuck with migrations. But works well with SQLite

**Comment by rriski** [comment]
Same issue with DjangoCMS 5.3.2, Django 1.11.15, Python 3.5.2 and MySQL 5.7.23. 

My allow migrate looks like this:
`def allow_migrate(self, db, app_label, model_name=None, **hints):
        if app_label == 'auth_x' or 'auth':
            return db == 'auth_db'

        if db == 'auth_db':
            return False
        return None`

**Comment by viten-center** [comment]
Same problem. I use:
django_cms-3.5.3
Django-1.11.18
PostgreSQL 10.5
everything is fine with SQLite

**Comment by benzkji** [comment]
same here, on a fresh cms 3.6.0 / dj 2.1 / postgres 9.6 install.

**Comment by benzkji** [comment]
though, mine doesnt throw the same error...but still, migrations 0019 looks like a problem kid? any reflections on this?

**Comment by jrief** [comment]
@benzkji This is a problem in `psycopg2-binary` introduced in version 2.8.
Downgrading to 2.7.7 solves it.

**Comment by benzkji** [comment]
aaahh. nice to know! many thanks!

**Comment by HT-Moh** [comment]
I just opened the file path/postgresql/introspection.py and replaced the return statement which gives an error on line 68 for me with the following code and everything worked

```
return [
                FieldInfo(
                    line.name,
                    line.type_code,
                    line.display_size,
                    line.internal_size,
                    line.precision,
                    line.scale,
                    *field_map[line.name],
            )
            for line in cursor.description
]

```

**Comment by pglotov** [comment]
I get this error with `psycopg2-binary==2.7.7`

**Comment by pglotov** [comment]
This [PR](https://github.com/divio/django-cms/pull/6707/files) fixed it for me.

**Comment by piotrekmonko** [comment]
> @benzkji This is a problem in `psycopg2-binary` introduced in version 2.8.
> Downgrading to 2.7.7 solves it.

Not using `psycopg2-binary` in my case but a multi db setup, same error. Seems migration 19 forgot to call router's `allow_migrate`.
