### ISSUE TITLE
Error on initial install on MySQL

### ISSUE THREAD

**Issue by ZippoLag** [django-cms/django-cms#6493]
### Summary

I've been using Django-CMS with a local SQLite DB without issues, but since my actual environments use MySQL, I tried running it in local and I'm getting errors with python manage.py migrate. For some reason, _sometimes_ the migration works fine, but most of the time it gets stuck on 0008.

### Expected behaviour

Initial migrate works fine

### Actual behaviour

(...)
  Applying cms.0008_auto_20150121_0059...C:\virtualenvs\exemplar3\lib\site-packages\django\db\backends\mysql\base.py:101
: Warning: (3719L, u"'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a f
uture release. Please consider using UTF8MB4 in order to be unambiguous.")
  return self.cursor.execute(query, args)
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_comman
d_line
    utility.execute()
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards

    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\migrations\migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\migrations\operations\models.py", line 536, in database_for
wards
    getattr(new_model._meta, self.option_name, set()),
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\backends\base\schema.py", line 365, in alter_unique_togethe
r
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\backends\mysql\schema.py", line 88, in _delete_composed_ind
ex
    return super(DatabaseSchemaEditor, self)._delete_composed_index(model, fields, *args)
  File "C:\virtualenvs\exemplar3\lib\site-packages\django\db\backends\base\schema.py", line 394, in _delete_composed_ind
ex
    ", ".join(columns),
ValueError: Found wrong number (0) of constraints for cms_page(publisher_is_draft, application_namespace)

### Environment

* Python version: 2.7.15
* Django version: 1.11
* django CMS version: 3.4.6

**Comment by renjithraj2005** [comment]
The same happening on Postgres too

**Comment by ZippoLag** [comment]
Hi @2martens, sorry, but no. I tried a couple of times but it's just entirely random, I've settled for just installing, if it fails I wipe the database, try again, and so on until I get a working install. I'll try again when I need to start a new project.

**Comment by Aiky30** [comment]
Does anyone still have this issue and if so can you provide database version numbers? I have seen issues with early migrations with MySQL 5.7 and early MariaDB versions. 

Closing due to the age and no activity on this issue. Happy to open it again if this affects anyone still or in the future.


Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
