### ISSUE TITLE
Migration error in  djangocms_snippet.0004_auto_alter_slug_unique with mysql-connector-python

### ISSUE THREAD

**Issue by ramilS** [django-cms/django-cms#6678]
```
 Applying djangocms_snippet.0004_auto_alter_slug_unique...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 221, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 531, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 594, in _alter_field
    index_names = self._constraint_names(model, [old_field.column], index=True, type_=Index.suffix)
  File "/Users/ramil/Documents/projects/air/env/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 1025, in _constraint_names
    if type_ is not None and infodict['type'] != type_:
KeyError: 'type'

```

dj-database-url==0.5.0
Django==1.11.20
django-classy-tags==0.8.0
django-cms==3.6.0
django-filer==1.4.4
django-formtools==2.1
django-js-asset==1.2.2
django-mptt==0.10.0
django-polymorphic==2.0.3
django-sekizai==1.0.0
django-treebeard==4.3
djangocms-admin-style==1.2.9
djangocms-attributes-field==1.1.0
djangocms-column==1.9.0
djangocms-file==2.2.0
djangocms-googlemap==1.2.0
djangocms-installer==1.1.0
djangocms-link==2.4.0
djangocms-picture==2.0.8
djangocms-snippet==2.1.0
djangocms-style==2.1.0
djangocms-text-ckeditor==3.7.0
djangocms-video==2.0.5
easy-thumbnails==2.6
html5lib==1.0.1
mysql-connector-python==8.0.16
Pillow==6.0.0
protobuf==3.7.1
pytz==2019.1
six==1.12.0
tzlocal==1.5.1
Unidecode==1.0.23
webencodings==0.5.1

**Comment by Aiky30** [comment]
Hello @ramilS,

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
