### ISSUE TITLE
Unable to use django-debug-toolbar together with django-cms

### ISSUE THREAD

**Issue by jonathan-s** [django-cms/django-cms#6731]
### Summary
When opening a cms page to edit the page fails

### Expected behaviour
You should be able to open a page and be able to see a working django-debug-toolbar. 

### Actual behaviour
It fails with the following traceback. 

```
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1  |     response = self.process_exception_by_middleware(e, request)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
web_1  |     return wrapped(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
web_1  |     return view(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/cms/views.py", line 237, in render_object_edit
web_1  |     toolbar.set_object(content_type_obj)
web_1  | AttributeError: 'EmptyToolbar' object has no attribute 'set_object'
```

### Environment

* Python version: 3.6
* Django version: 1.11
* django CMS version: 4.0

**Comment by Aiky30** [comment]
@jonathan-s I have a document that I can share with you regarding django-debug-toolbar setup both standalone and in the Divio cloud setup. Please reach out if that is ever required again.

**Comment by jonathan-s** [comment]
Since there is such a document perhaps that should be a part of the
documentation?

**Comment by Aiky30** [comment]
@jonathan-s the information is already part of the debug toolbars docs, it needs additional settings for the cloud, it doesn't belong in the CMS as it is a third party.

**Comment by Aiky30** [comment]
@magicproductions, to rephrase your request: @Aiky30 Can you please provide that information here?

@Aiky30: Sure.

Note: This is for a Divio Cloud project with django-cms. 

**Django 2.2+**
Modify urls.py of the project by adding:

```
import settings

if settings.DEBUG:
    from django.urls import path
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
```

At the bottom of requirements.in
```
django-debug-toolbar
```

At the bottom of the settings.py file
```
########################
# Django Debug Toolbar
########################
INSTALLED_APPS.extend([
    # add your project specific apps here
    'debug_toolbar',
])
MIDDLEWARE.insert(
    MIDDLEWARE.index('django.middleware.gzip.GZipMiddleware') + 1,
    'debug_toolbar.middleware.DebugToolbarMiddleware'
)
INTERNAL_IPS = ('127.0.0.1', 'localhost', '0.0.0.0',)
def show_toolbar(request):
    return True
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': show_toolbar,
    'RESULTS_CACHE_SIZE': 500
}
```

**Django 1.11**
Modify urls.py of the project by adding:
```
import settings
if settings.DEBUG:
    from django.conf.urls import url
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
```

At the bottom of requirements.in
```
django-debug-toolbar
```

At the bottom of the settings.py file
```
########################
# Django Debug Toolbar
########################
INSTALLED_APPS.extend([
    # add your project specific apps here
    'debug_toolbar',
])
MIDDLEWARE_CLASSES.insert(
    MIDDLEWARE_CLASSES.index('django.middleware.gzip.GZipMiddleware') + 1,
    'debug_toolbar.middleware.DebugToolbarMiddleware'
)
INTERNAL_IPS = ('127.0.0.1', 'localhost', '0.0.0.0',)
def show_toolbar(request):
    return True
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': show_toolbar,
    'RESULTS_CACHE_SIZE': 500
}
```
