### ISSUE TITLE
[BUG] `ProgrammingError` on migrate when system check causes db query in raw_id_fields property

### ISSUE THREAD

**Issue by stefanw** [django-cms/django-cms#7103]
## Description

The exception (see stack trace below) is generated by a system check that checks raw id fields which in django CMS does a database query(!):

https://github.com/django-cms/django-cms/blob/release/3.9.x/cms/admin/permissionadmin.py#L158-L173

This function already expects an exception during migrate, but only an `OperationalError`. Apparently it also needs to catch a `ProgrammingError`. They both inherit from `DatabaseError`, but that might be to generic to mask here, feels quite brittle.

IMHO, `CMS_RAW_ID_USERS` should move from a threshold value that is measured at runtime to a boolean flag to avoid database queries.

## Steps to reproduce

Setup existing project with Django-CMS, custom user model and empty DB.
Run `./manage.py migrate`

## Expected behaviour

Migrations run.

## Actual behaviour

```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "lib/python3.9/site-packages/django/contrib/admin/checks.py", line 54, in check_admin_app
    errors.extend(site.check(app_configs))
  File "lib/python3.9/site-packages/django/contrib/admin/sites.py", line 92, in check
    errors.extend(modeladmin.check())
  File "lib/python3.9/site-packages/django/contrib/admin/options.py", line 122, in check
    return self.checks_class().check(self, **kwargs)
  File "lib/python3.9/site-packages/django/contrib/admin/checks.py", line 642, in check
    *super().check(admin_obj),
  File "lib/python3.9/site-packages/django/contrib/admin/checks.py", line 151, in check
    *self._check_raw_id_fields(admin_obj),
  File "lib/python3.9/site-packages/django/contrib/admin/checks.py", line 224, in _check_raw_id_fields
    if not isinstance(obj.raw_id_fields, (list, tuple)):
  File "lib/python3.9/site-packages/cms/utils/helpers.py", line 39, in __get__
    return self.fget(owner_cls)
  File "lib/python3.9/site-packages/cms/admin/permissionadmin.py", line 169, in raw_id_fields
    threshold = threshold and get_user_model().objects.count() > threshold
  File "lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/python3.9/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "lib/python3.9/site-packages/django/db/models/sql/query.py", line 519, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "lib/python3.9/site-packages/django/db/models/sql/query.py", line 504, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "account_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "account_user"
```

## Additional information (CMS/Python/Django versions)

Django-CMS==3.9.0
Django==3.2.4
Python 3.8

**Comment by Aiky30** [comment]
I am guessing that you are extending the user model with your own extended user model, if that is indeed the case try and run the migrations with RAW_ID_USERS = False, and or removing the setting that sets the custom user model. Once you get the migrations to run the model exists it should then start to work with your current overrides / settings.

**Comment by stefanw** [comment]
@Aiky30 Thanks, it worked with `./manage.py --skip-checks`. I wanted to raise this issue given the (incomplete) workaround present in the code.
