### ISSUE TITLE
[BUG] Exception Type: InterfaceError Exception Value: cursor already closed

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [django-cms/django-cms#7320]
## Description

Quite often standard django cms drop exception InterfaceError Exception Value: cursor already closed during adding new plugins during edition of pages. 

## Steps to reproduce

Random but often

## Expected behaviour
have to work normally 

## Actual behaviour

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)

The above exception (cursor already closed) was the direct cause of the following exception:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/classytags/core.py", line 151, in render
    return self.render_tag(context, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sekizai/templatetags/sekizai_tags.py", line 87, in render_tag
    rendered_contents = nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/classytags/core.py", line 151, in render
    return self.render_tag(context, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cms/templatetags/cms_tags.py", line 443, in render_tag
    return toolbar.render_with_structure(context, nodelist)
  File "/usr/local/lib/python3.9/site-packages/cms/toolbar/toolbar.py", line 476, in render_with_structure
    rendered_contents = nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/classytags/core.py", line 151, in render
    return self.render_tag(context, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cms/templatetags/cms_tags.py", line 305, in render_tag
    content = renderer.render_page_placeholder(
  File "/usr/local/lib/python3.9/site-packages/cms/plugin_rendering.py", line 327, in render_page_placeholder
    self._preload_placeholders_for_page(current_page)
  File "/usr/local/lib/python3.9/site-packages/cms/plugin_rendering.py", line 522, in _preload_placeholders_for_page
    assign_plugins(
  File "/usr/local/lib/python3.9/site-packages/cms/utils/plugins.py", line 74, in assign_plugins
    plugin_groups = dict((key, list(plugins)) for key, plugins in groupby(plugins, attrgetter('placeholder_id')))
  File "/usr/local/lib/python3.9/site-packages/cms/utils/plugins.py", line 74, in <genexpr>
    plugin_groups = dict((key, list(plugins)) for key, plugins in groupby(plugins, attrgetter('placeholder_id')))
  File "/usr/local/lib/python3.9/site-packages/cms/utils/plugins.py", line 284, in downcast_plugins
    for instance in plugin_qs.iterator():
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 360, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 70, in __iter__
    for row in compiler.results_iter(results):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1096, in apply_converters
    for row in map(list, rows):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1606, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1606, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)

Exception Type: InterfaceError at /en/products/equipment-thermal-cutting/
Exception Value: cursor already closed
```

## Additional information (CMS/Python/Django versions)

used standard django cms quickstart repo. 

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by jpVm5jYYRE1VIKL** [comment]
Same on postgre sql 14.4 
django=3.2 
django cms = 3.10.1

**Comment by marksweb** [comment]
@jpVm5jYYRE1VIKL This is likely a configuration issue with the web server.

Have a read of this; https://forum.djangoproject.com/t/db-connection-closed-by-uwsgi-in-the-middle-of-handling-a-request/9875/6

**Comment by jpVm5jYYRE1VIKL** [comment]
@marksweb Most probabaly. But it happens with  django-cms-quickstart standard project.  So it does not have any specific settings.

**Comment by marksweb** [comment]
@jpVm5jYYRE1VIKL how are you running the quickstart project when you hit this error?

**Comment by jpVm5jYYRE1VIKL** [comment]
@marksweb . Quite simple steps. 
Of course i added my own templates and menu. 
I also updated some libs in requirements.in (compiled it with pip-compile requirements.in >> requirements.txt)
and also updated postgre separate image from 9.6-alpine to 14.4-alpine (because thought that may be issue binded with 9.6 pgre )

I build using Dockerfile image . 
after it assign tag to image and publish to registry 
after it i deploy image using compose using docker-compose.yml as an example (with adjustments about fresh built image , published port and  pgre vestion). 

 this is my compose : 

```
version: "3"

services:
  web:
    image: registry.mydomain.net/proj_web:1.1.6
    # map the internal port 80 to port 8000 on the host
    ports:
      - "28000:80"
    # map the host directory to app (which allows us to see and edit files inside the container)
    volumes:
      - "./data:/data:rw"
      - "./conf/settings.py:/app/backend/settings.py:ro"
      - "./logs:/logs:rw"
    # the default command to run whenever the container is launched
    command: uwsgi --http=0.0.0.0:80 --module=backend.wsgi --check-static=/data
    # command: python manage.py runserver 0.0.0.0:80
    # the URL 'postgres' or 'mysql' will point to the application's db service
    networks:
      - djangocmsnet

    env_file: .env-local

  database_default:
    # Select one of the following db configurations for the database
    image: postgres:14.4-alpine
    ports:
      - "5432:5432/tcp"  # allow your local dev env to connect to the db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"

    networks:
      - djangocmsnet

networks:
  djangocmsnet:
```
