### ISSUE TITLE
[BUG] "django.db.utils.OperationalError: error in index cms_cmsplugin_level_0ccc318d after drop column: no such column: level"

### ISSUE THREAD

**Issue by jamalex** [django-cms/django-cms#7375]
## Description

I started a new project, following the virtualenv instructions, and sqlite. When trying to run migrations, it fails when trying to drop what appear to be old MPTT fields (level, lft, rght, etc), which don't appear to exist:

```
Applying cms.0006_auto_20140924_1110...Traceback (most recent call last):
  File "<redacted>/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "<redacted>/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: error in index cms_cmsplugin_level_0ccc318d after drop column: no such column: level

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamalex/fle/learningequality.org-v3/le_cms/manage.py", line 22, in <module>
    main()
  File "/home/jamalex/fle/learningequality.org-v3/le_cms/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "<redacted>/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "<redacted>/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "<redacted>/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "<redacted>/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "<redacted>/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "<redacted>/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "<redacted>/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "<redacted>/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "<redacted>/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "<redacted>/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "<redacted>/site-packages/django/db/migrations/operations/fields.py", line 170, in database_forwards
    schema_editor.remove_field(
  File "<redacted>/site-packages/django/db/backends/sqlite3/schema.py", line 417, in remove_field
    super().remove_field(model, field)
  File "<redacted>/site-packages/django/db/backends/base/schema.py", line 720, in remove_field
    self.execute(sql)
  File "<redacted>/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "<redacted>/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "<redacted>/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "<redacted>/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "<redacted>/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "<redacted>/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "<redacted>/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "<redacted>/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: error in index cms_cmsplugin_level_0ccc318d after drop column: no such column: level
```

## Steps to reproduce

Followed the instructions at https://docs.django-cms.org/en/latest/how_to/install.html#installation

with settings:

```
"""
Django settings for le_cms project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "<redacted>"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    "djangocms_admin_style",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "cms",
    "menus",
    "treebeard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "le_cms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "le_cms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGES = [
    ("en", "English"),
    ("es", "Español"),
]

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
```

## Expected behaviour

Successful migration run.

## Actual behaviour

Traceback shown above is displayed, and migrations are interrupted. Deleting the database and trying to migrate again gives the same result.

## Additional information (CMS/Python/Django versions)

```
$ python -V
Python 3.9.7

$ pip freeze
asgiref==3.5.2
Django==4.1
django-classy-tags==3.0.1
django-cms==3.11.0
django-formtools==2.3
django-sekizai==4.0.0
django-treebeard==4.5.1
djangocms-admin-style==3.2.0
```

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by jamalex** [comment]
I note that commenting out these lines in the migration allow it to complete, but I'm not sure whether that would cause other issues down the line:

```
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20140924_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('path',), 'verbose_name': 'page', 'verbose_name_plural': 'pages', 'permissions': (('view_page', 'Can view page'), ('publish_page', 'Can publish page'), ('edit_static_placeholder', 'Can edit static placeholders'))},
        ),
        # migrations.RemoveField(
        #     model_name='cmsplugin',
        #     name='level',
        # ),
        # migrations.RemoveField(
        #     model_name='cmsplugin',
        #     name='lft',
        # ),
        # migrations.RemoveField(
        #     model_name='cmsplugin',
        #     name='rght',
        # ),
        # migrations.RemoveField(
        #     model_name='cmsplugin',
        #     name='tree_id',
        # ),
        # migrations.RemoveField(
        #     model_name='page',
        #     name='level',
        # ),
        # migrations.RemoveField(
        #     model_name='page',
        #     name='lft',
        # ),
        # migrations.RemoveField(
        #     model_name='page',
        #     name='rght',
        # ),
        # migrations.RemoveField(
        #     model_name='page',
        #     name='tree_id',
        # ),
        migrations.AlterField(
            model_name='cmsplugin',
            name='depth',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='cmsplugin',
            name='numchild',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cmsplugin',
            name='path',
            field=models.CharField(unique=True, max_length=255, editable=False),
        ),
    ]
```

**Comment by jamalex** [comment]
Sorry, I missed this line in one of the callouts on the instructions page:
>For the cms to work correctly, you will need django version 3.2. Work with newer versions can be unstable.

I downgraded to Django 3.2 and it no longer gave this error with the original migration. Sorry!

**Comment by marksweb** [comment]
@jamalex I note the settings generated using django 4.1. I think django-cms 3.11 supports 4.0, but I don't think we support 4.1 yet.
