### ISSUE TITLE
[BUG] management command "cms check" doesn't work (again).

### ISSUE THREAD

**Issue by mbi** [django-cms/django-cms#7386]
## Description

This appears to be exactly the same bug that was fixed in #7033: 

When running the subcommand, [this line](https://github.com/django-cms/django-cms/blob/develop/cms/management/commands/subcommands/base.py#L39) doesn't check for `DJANGO_4_0`, so the command fails with 

```
  File "/home/marco/Code/kavea/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 453, in execute
    if self.requires_system_checks and not options["skip_checks"]:
KeyError: 'skip_checks'
``` 

## Steps to reproduce

1. Install django-cms==3.11 and Django==4.0
2. python manage.py cms check

**Comment by weeser** [comment]
I am also getting this error, but with django 4.1.1:

(venv) A:\workspace\>python manage.py cms fix-tree
Traceback (most recent call last):
  File "A:\workspace\manage.py", line 22, in <module>
    main()
  File "A:\workspace\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "A:\workspace\env\venv\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "A:\workspace\env\venv\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "A:\workspace\env\venv\lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "A:\workspace\env\venv\lib\site-packages\django\core\management\base.py", line 441, in execute
    if self.requires_system_checks and not options["skip_checks"]:
KeyError: 'skip_checks'
