### ISSUE TITLE
[BUG] Invalid block tag on line 101: 'page_submit_row', expected 'endif'

### ISSUE THREAD

**Issue by manyacz** [django-cms/django-cms#7398]
## Description

```
<html><body>
<!--StartFragment--><div id="summary">
  <h1>TemplateSyntaxError
       at /admin/cms/pagetype/add/</h1>
  <pre class="exception_value">Invalid block tag on line 101: 'page_submit_row', expected 'endif'. Did you forget to register or load this tag?</pre>
  

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/cms/pagetype/add/
4.1.1
TemplateSyntaxError
Invalid block tag on line 101: 'page_submit_row', expected 'endif'. Did you forget to register or load this tag?
C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py, line 558, in invalid_block_tag
cms.admin.pageadmin.add_view
C:\Users\manyacz\dj_project\.venv\Scripts\python.exe
3.10.5
['C:\\Users\\manyacz\\dj_project\\viar',  'C:\\Users\\manyacz\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',  'C:\\Users\\manyacz\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',  'C:\\Users\\manyacz\\AppData\\Local\\Programs\\Python\\Python310\\lib',  'C:\\Users\\manyacz\\AppData\\Local\\Programs\\Python\\Python310',  'C:\\Users\\manyacz\\dj_project\\.venv',  'C:\\Users\\manyacz\\dj_project\\.venv\\lib\\site-packages']
Tue, 20 Sep 2022 09:59:16 +0000


</div>



<div id="template">
   <h2>Error during template rendering</h2>
   <p>In template <code>C:\Users\manyacz\dj_project\.venv\lib\site-packages\cms\templates\admin\cms\page\change_form.html</code>, error at line <strong>101</strong></p>
   <h3>Invalid block tag on line 101: 'page_submit_row', expected 'endif'. Did you forget to register or load this tag?</h3></div><!--EndFragment-->
</body>
</html>
```

```
Traceback (most recent call last):
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'page_submit_row'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\defaulttags.py", line 968, in do_if
    nodelist = parser.parse(("endif",))
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\manyacz\dj_project\.venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 101: 'page_submit_row', expected 'endif'. Did you forget to register or load this tag?
[20/Sep/2022 13:59:16] "GET /admin/cms/pagetype/add/ HTTP/1.1" 500 219573

```

```
(.venv) C:\Users\manyacz\dj_project\viar>pip list
Package               Version
--------------------- -------
asgiref               3.5.2
Django                4.1.1
django-classy-tags    3.0.1
django-cms            3.11.0
django-formtools      2.3
django-sekizai        4.0.0
django-treebeard      4.5.1
djangocms-admin-style 3.2.0
pip                   22.2.2
setuptools            58.1.0
sqlparse              0.4.2
tzdata                2022.2
```

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
This will be solved by #7404
