### ISSUE TITLE
thumbnail is missing... [BUG]

### ISSUE THREAD

**Issue by prepstarr** [django-cms/django-cms#7627]
## Description
thumbnail image in the preview section is missing ...

![image](https://github.com/django-cms/django-cms/assets/65930206/00544e90-a542-4570-bbfb-5935de4abf09)

## Expected behaviour

thumbnail should show image

show image
## Actual behaviour
broken link

```
FILER_STORAGES = {
    'public': {
            'OPTIONS': {
                'location': '/home/sixpiece/python/emploiquebec/media/filer',
                'base_url': '/media/filer/',
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_public',
        },
        'thumbnails': {
                'location': '/home/sixpiece/python/emploiquebec/media/filer_thumbnails',
                'base_url': '/media/filer_thumbnails/',
            },
        },
    },
    'private': {
        'main': {
            'ENGINE': 'filer.storage.PrivateFileSystemStorage',
            'OPTIONS': {
                'location': '/usr/home/sixpiece/python/emploiquebec/smedia/filer',
                'base_url': '/smedia/filer/',
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_public',
        },
        'thumbnails': {
            'ENGINE': 'filer.storage.PrivateFileSystemStorage',
            'OPTIONS': {
                'location': '/usr/home/sixpiece/python/emploiquebec/smedia/filer_thumbnails',
                'base_url': '/smedia/filer_thumbnails/',
            },
        },
    },
} 
```in settings.py

this directory exists : ```
/home/sixpiece/python/emploiquebec/media/filer_thumbnails/filer_public_thumbnails/filer_public/fb/5b/fb5bdd6d-9a78-4a7c-ab42-39c41d3b510b this directory exists and the following files exist: sheldon-lub.png__160x160_q85_crop_subsampling-2.jpg
sheldon-lub.png__180x180_q85_crop_subsampling-2_upscale.jpg
sheldon-lub.png__40x40_q85_crop_subsampling-2.jpg
sheldon-lub.png__70x70_q85_crop_subsampling-2.jpg
sheldon-lub.png__70x70_q85_subsampling-2.jpg
sheldon-lub.png__80x80_q85_crop_subsampling-2.jpg
```

it looks like it's close but for some reason thumbnail is not generated...

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Can you share your MEDIA settings?

**Comment by prepstarr** [comment]
Yes my apologies for the late return if this is not the right answer, I will be back at it on Saturday night... I was up late that night and did an hour sieste now but I want to finish making my soup , etc..

# adding MEDIA root
MEDIA_ROOT = '/usr/home/sixpiece/python/emploiquebec/media'

MEDIA_URL = '/media/'e__).resolve().parent.parent

**Comment by fsbraun** [comment]
The `MEDIA_URL` line seems crumbled... at least by the balance of opening and closing brackets?

**Comment by prepstarr** [comment]
sorry about that there was probably something wrong with how it posted...

# adding MEDIA root
MEDIA_ROOT = '/usr/home/sixpiece/python/emploiquebec/media'

MEDIA_URL = '/media/'

**Comment by prepstarr** [comment]
```
from pathlib import Path

import os.path

USE_TZ = False

FILER_CANONICAL_URL = 'canonical/'

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'd87%15x3pBU7*k&@L11PkBtn38oQiNhJ2IX9iqA8d0p%sfikc2m@5p'

DEBUG = True
ALLOWED_HOSTS = [
   'emploisquebec.net'
]


# Application definition

INSTALLED_APPS = [
    'debug_toolbar',
    'filemanager',
    'filer',
    'easy_thumbnails',
    'emplois.apps.EmploisConfig',
    'splashpage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'emploiquebec.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

FILER_SERVERS = {
    'private': {
        'main': {
            'ENGINE': 'filer.server.backends.xsendfile.ApacheXSendfileServer',
            },
        'thumbnails': {
            'ENGINE': 'filer.server.backends.xsendfile.ApacheXSendfileServer',
            },
        },
    }

WSGI_APPLICATION = 'emploiquebec.wsgi.application'

MEDIA_ROOT = '/usr/home/sixpiece/python/emploiquebec/media'

MEDIA_URL = '/media/'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

FILER_ENABLE_PERMISSIONS = True

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },
]


LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Berlin/Europe'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FILER_STORAGES = {
    'public': {
        'main': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {
                'location': '/home/sixpiece/python/emploiquebec/media/filer',
                'base_url': '/media/filer/',
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_public',
        },
        'thumbnails': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {
                'location': '/home/sixpiece/python/emploiquebec/media/filer_thumbnails',
                'base_url': '/media/filer_thumbnails/',
            },
        },
    },
    'private': {
        'main': {
            'ENGINE': 'filer.storage.PrivateFileSystemStorage',
            'OPTIONS': {
                'location': '/usr/home/sixpiece/python/emploiquebec/smedia/filer',
                'base_url': '/smedia/filer/',
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_public',
        },
        'thumbnails': {
            'ENGINE': 'filer.storage.PrivateFileSystemStorage',
            'OPTIONS': {
                'location': '/usr/home/sixpiece/python/emploiquebec/smedia/filer_thumbnails',
                'base_url': '/smedia/filer_thumbnails/',
            },
        },
    },
}
```

**Comment by prepstarr** [comment]
here's the issue as far as I see... is the thumbnail

'filer.thumbnail_processors.scale_and_crop_with_subject_location', will not work but if I use 

'easy_thumbnails.processors.scale_and_crop', then it works.... cause it gives a different location

**Comment by prepstarr** [comment]
for example it looks for this thumbnail : https://tld-withheld.net/media/filer_public_thumbnails/filer_public/fb/5b/fb5bdd6d-9a78-4a7c-ab42-39c41d3b510b/sheldon-lub.png__40x40_q85_crop_subsampling-2.jpg

sheldon-lub.png__40x40_q85_crop_subsampling-2.jpg a little bit odd...

**Comment by prepstarr** [comment]
I set it back to 'filer.thumbnail_processors.scale_and_crop_with_subject_location' what I notice is that the minute it uploads the picture it's there but if I refresh it's gone...

**Comment by prepstarr** [comment]
```
(env) $ python manage.py filer_check --orphans
Traceback (most recent call last):
  File "/usr/home/sixpiece/python/emploiquebec/manage.py", line 22, in <module>
    main()
  File "/usr/home/sixpiece/python/emploiquebec/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/filer/management/commands/filer_check.py", line 66, in handle
    self.verify_storages(options)
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/filer/management/commands/filer_check.py", line 114, in verify_storages
    walk(filer_public['UPLOAD_TO_PREFIX'])
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/filer/management/commands/filer_check.py", line 95, in walk
    child_dirs, files = storage.listdir(prefix)
  File "/usr/home/sixpiece/env/lib/python3.9/site-packages/django/core/files/storage/filesystem.py", line 170, in listdir
    with os.scandir(path) as entries:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/home/sixpiece/python/emploiquebec/media/filer_public'
```

**Comment by prepstarr** [comment]
apologize for the fatigure of the other I was up late doing the system upgrades, etc..

**Comment by prepstarr** [comment]
it's missing filer_thumbnails in the path... between /media/"missing here"/filer_public_thumbnails ...

**Comment by fsbraun** [comment]
Just to nail this down: I assume the issue disappears if you remove your custom thumbnail filer storage? If so, I assume there is a bug using the wrong storage.

**Comment by prepstarr** [comment]
I believe that is correct, I will double check, although that is on any new pictures added not the old ones done with filer... .. it just needs that /media/_______/filer_public_thumbnails.... where _____ = filer_thumbnails

**Comment by prepstarr** [comment]
no it's maybe not it doesn't seem to work any different with easy thumbnails although it will show the picture without the refresh...

**Comment by prepstarr** [comment]
yes that is correct, on new pictures if I comment out the thumbnail storage it will work properly...

**Comment by prepstarr** [comment]
it seems to fix the issue... in fact because by selecting the image it will recreate the thumbnail and it will work... should I close this issue?

**Comment by prepstarr** [comment]
thank you...

**Comment by prepstarr** [comment]
![image](https://github.com/django-cms/django-cms/assets/65930206/142dc307-55c5-43d5-90b8-8919c905498d)

**Comment by fsbraun** [comment]
I think you found a real bug: If you have a custom file storage for thumbnails, it needs to be reflected in the directory listing. Leave this issue open.

**Comment by fsbraun** [comment]
I would like to come up with a fix. Once I've done that, could you test it with your original settings?
