### ISSUE TITLE
[BUG]Cache key errors with memcached

### ISSUE THREAD

**Issue by pgcd** [django-cms/django-cms#7690]
## Description

Using memcached, I'm getting random errors that look like 

```
Exception Type: KeyError at /
Exception Value: b':2:cms_3.11.3_:1:42099b4af021e53fd8fd4e056c2568d7c2e3ffa8:it.Europe/Rome'
```

These errors only started appearing when I switched from `pylibmc` to `pymemcache` - before that, the errors were different: 

```
InvalidCacheKey at /
Cache key contains characters that will cause errors if used with memcached: ':(1694945034098176, []):cms_3.11.0_:1:42099b4af021e53fd8fd4e056c2568d7c2e3ffa8:it.Europe/Rome'
```
and 
```
Exception Type: MemcachedKeyLengthError at /
Exception Value: Key length is > 250
```

I have been unable to understand *what* causes these errors, as there's no way of reproducing them locally and the error doesn't occur twice in the same page (or doesn't occur with users that are different from the one that caused the error).

## Steps to reproduce

The error is unfortunately random and I have found no reproducible way of causing it - visiting the same page I have in the error report, for instance, works normally

## Expected behaviour

No server error due to cache keys

## Actual behaviour

Random server errors due to cache keys

## Additional information (CMS/Python/Django versions)

Django Version: 4.2.4
Python Version: 3.8.10
Django CMS version: 3.11.3

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
The issue of cache keys longer than 250 characters for placeholder cache keys has been fixed in #7657 and will be part of the next minor 3.11 release.

Having said this, your current error comes from a page cache key. I'm unclear where the key error happens. The key looks ok to me at first sight. Do you have a stack trace?

**Comment by pgcd** [comment]
I'm sorry, I thought I replied but it looks like something ate my post.

Here are a couple stack traces:

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/sekizai/templatetags/sekizai_tags.py", line 87, in render_tag
    rendered_contents = nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/cms/templatetags/cms_tags.py", line 433, in render_tag
    return nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/classytags/helpers.py", line 41, in render_tag
    value = self.get_value(context, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/cms/templatetags/cms_tags.py", line 226, in get_value
    url = get_page_url_cache(page_lookup, lang, site_id)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/cms/cache/page.py", line 137, in get_page_url_cache
    return cache.get(_page_url_key(page_lookup, lang, site_id),
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    return self._cache.get(key, default)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/hash.py", line 347, in get
    return self._run_cmd("get", key, default, default=default, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
    return self._safely_run_func(client, func, default_val, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/hash.py", line 211, in _safely_run_func
    result = func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/base.py", line 687, in get
    return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/base.py", line 1153, in _fetch_cmd
    key, value, buf = self._extract_value(
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/base.py", line 1107, in _extract_value
    original_key = remapped_keys[key]

Exception Type: KeyError at /gioca-con-noi/parole-crociate/
Exception Value: b':1:cms_3.11.3__PAGE_CACHE_VERSION'
```

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 79, in super
    return mark_safe(self.render(self.context))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/classytags/core.py", line 151, in render
    return str(self.render_tag(context, **kwargs))
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/classytags/helpers.py", line 41, in render_tag
    value = self.get_value(context, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/cms/templatetags/cms_tags.py", line 226, in get_value
    url = get_page_url_cache(page_lookup, lang, site_id)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/cms/cache/page.py", line 138, in get_page_url_cache
    version=_get_cache_version())
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/cms/cache/__init__.py", line 15, in _get_cache_version
    version = cache.get(CMS_PAGE_CACHE_VERSION_KEY)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    return self._cache.get(key, default)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/hash.py", line 347, in get
    return self._run_cmd("get", key, default, default=default, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
    return self._safely_run_func(client, func, default_val, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/hash.py", line 211, in _safely_run_func
    result = func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/base.py", line 687, in get
    return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
  File "/home/ubuntu/.virtualenvs/aenew/lib/python3.8/site-packages/pymemcache/client/base.py", line 1165, in _fetch_cmd
    raise MemcacheUnknownError(line[:32])

Exception Type: MemcacheUnknownError at /shop/catalogue/abbonamento-la-settimana-enigmistica-italia_4/
Exception Value: b'bhS)\x81\x94}\x94(hV\x8c\x16termini-condizioni-'
Raised during: oscar.apps.catalogue.views.view
```

Note that the second is raised from django-oscar, which we have installed as a CMS app.

**Comment by fsbraun** [comment]
@pgcd The key `':1:cms_3.11.3__PAGE_CACHE_VERSION'` looks OK to me. Are you using a [KEY_PREFIX](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-CACHES-KEY_PREFIX) in your config? Somehow pymemcache seems to stumble when resolving the `key_prefix`.

The Oscar key contains non-ASCII letters which, if I'm correct, are not supported by pymemcache.

**Comment by pgcd** [comment]
No, no KEY_PREFIX in settings.
What's interesting is that the cache key itself seems to work:
```
from django.core.cache import cache
cache.get(b'bhS)\x81\x94}\x94(hV\x8c\x16termini-condizioni-')  # outputs None
cache.set(b'bhS)\x81\x94}\x94(hV\x8c\x16termini-condizioni-', "test")
cache.get(b'bhS)\x81\x94}\x94(hV\x8c\x16termini-condizioni-')  # outputs 'test'
```
So I'm thinking that the problem is twofold:
1. for some reason the CMS is building cache keys that include unexpected characters (Oscar itself only caches products and uses a very predictable key (`cache_key = "CATEGORY_URL_%s_%s" % (current_locale, self.pk)`) which doesn't look anything like the ones I'm getting errors from; also, the errors aren't limited to Oscar. This caused the problems with `pylibmc`
2. PyMemCache doesn't play well with `cache_page`, it seems https://github.com/pinterest/pymemcache/issues/450 

I see how the second problem is outside the scope of `django-cms`, but perhaps the first could be addressed here? 
I'd be happy to help, but I have no idea how to reproduce this and I'm not sure if using django-cms-transfer or something like that would actually copy the whole page structure and data.
