### ISSUE TITLE
fresh installtion of djangocms v4.1 generate error: no module named reportlab

### ISSUE THREAD

**Issue by i-salameh95** [django-cms/django-cms#7861]
## Description

after fresh installation of django cms 4.1 on Windows machine and python v3.9, when I try this command 
`djangocms mysite` 

it generates the following error: 
`
ModuleNotFoundError: No module named 'reportlab'`
## Steps to reproduce

1. Go to `https://www.django-cms.org/en/django-cms-4/` 
2. Scroll down to "Install django CMS 4.1 locally"
3. I have applied the commands described
4. See the error screenshot1 &2

## Expected behavior
if the **reportlab** and **svglib**  is mandatory packages for django-cms, so then why its not in put in the requirements ? 

## Actual behavior

error generated  shown in the screenshot, after I have make pip install reportlab, and redo the command: `djangocms mysite `
another error appear "` no module named svglib`", then I install it by pip install svglib 
then I continuo redo djangocms mysite, and the installation works like a charm. 

## Screenshots
![Capture](https://github.com/django-cms/django-cms/assets/78903915/fffbece4-10bd-43fc-a861-a47585198bec)
![svg](https://github.com/django-cms/django-cms/assets/78903915/7b7416a0-5789-44e4-8897-31bf8a8a058e)

## Do you want to help fix this issue?

* [] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@i-salameh95 Good to hear from you! I just tried with python 3.9 and it worked just fine.

Some quick checks:
* You did activate the fresh virtual environment? 
* The `djangocms` installs all requirements before running migrations. Did you see any error message? The output should look something like this:
```
Clone template using django-admin
django-admin startproject "mysite" --template https://github.com/django-cms/cms-template/archive/4.1.tar.gz
cd "/private/tmp/test/mysite"

Install requirements in /private/tmp/test/mysite/requirements.in
python -m pip install -r "/private/tmp/test/mysite/requirements.in"

Run migrations
python -m manage migrate
```

**Comment by i-salameh95** [comment]
- yes sure, I have activate the virtual env before doing any pip commands. 
- the error appear exactly like this: 

```
(.venv) C:\Users\Israa\projects\nnuh-website-4.1>djangocms mysite

Clone template using django-admin
django-admin startproject "mysite" --template https://github.com/django-cms/cms-template/archive/4.1.tar.gz
cd "C:\Users\Israa\projects\nnuh-website-4.1\mysite"

Install requirements in C:\Users\Israa\projects\nnuh-website-4.1\mysite\requirements.in
python -m pip install -r "C:\Users\Israa\projects\nnuh-website-4.1\mysite\requirements.in"

Run migrations
python -m manage migrate
Traceback (most recent call last):
  File "C:\Users\Israa\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Israa\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Israa\projects\nnuh-website-4.1\mysite\manage.py", line 22, in <module>
    main()
  File "C:\Users\Israa\projects\nnuh-website-4.1\mysite\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Israa\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\filer\models\__init__.py", line 4, in <module>
    from .imagemodels import *  # noqa
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\filer\models\imagemodels.py", line 9, in <module>
    from .abstract import BaseImage
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\filer\models\abstract.py", line 10, in <module>
    from easy_thumbnails.VIL import Image as VILImage
  File "c:\users\israa\projects\nnuh-website-4.1\.venv\lib\site-packages\easy_thumbnails\VIL\Image.py", line 7, in <module>
    from reportlab.graphics import renderSVG
ModuleNotFoundError: No module named 'reportlab'
CommandError: c:\users\israa\projects\nnuh-website-4.1\.venv\scripts\python.exe -m manage migrate failed.
```

Also I have attached 6 screenshots of the whole tries, that I have done each time, hopefully it will help. 
I think the requirements.in should include reportlab and svglib 

![1](https://github.com/django-cms/django-cms/assets/78903915/9fc89b70-6572-400c-bb5b-855b9f957b1a)
![2](https://github.com/django-cms/django-cms/assets/78903915/1fc3e9e7-cc9a-4d7e-a133-cfd88633de76)
![3](https://github.com/django-cms/django-cms/assets/78903915/54e0d167-078c-4997-9eef-e16033b71403)
![4](https://github.com/django-cms/django-cms/assets/78903915/96f9ecc5-1fa9-4ef8-a854-7f340ceacd6d)
![5](https://github.com/django-cms/django-cms/assets/78903915/bb4ee00c-efad-40ac-86d9-23c781abe174)
![6](https://github.com/django-cms/django-cms/assets/78903915/3d05f50f-870e-443c-b26f-1a3940109e2a)

**Comment by fsbraun** [comment]
Both reportlab and svglib should be installed automatically: They are indirect dependencies. Can you check which version of django-filer and easy-thumbnails gets installed?
