### ISSUE TITLE
[BUG] AttributeError: 'PlaceholderField' object has no attribute 'run_checks'

### ISSUE THREAD

**Issue by zmara** [django-cms/django-cms#7934]
## Description
Error AttributeError: 'PlaceholderField' object has no attribute 'run_checks'
is thrown when editing plugin:

```
from typing import Dict

from adminsortable2.admin import SortableInlineAdminMixin
from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from core.models import (
    ButtonBaseModel,
    FooterColumnLink,
    FooterColumnPluginModel,
    FooterLink,
    FooterPluginModel,
    FooterSocialNetwork,
    LinkIncludeOptionalButtonBaseModel,
    SectionBaseModel,
    MarginBaseModel,
    PaddingBaseModel
)
from django.contrib import admin


class NordicCMSPluginBase(CMSPluginBase):
    """
    Base class for all plugins with some goodies
    """

    @property
    def name(self):
        raise NotImplementedError()

    def render(self, context, instance, placeholder) -> Dict:
        context = super().render(context, instance, placeholder) or {}
        context["plugin_name"] = self.name
        return context

    def get_fieldsets(self, request, obj=None):
        if issubclass(self.model, LinkIncludeOptionalButtonBaseModel):
            button_fields = ["label", "style", "open_in_new_window", "external_link", "internal_link"]
        elif issubclass(self.model, ButtonBaseModel):
            button_fields = ["label", "style"]
        else:
            button_fields = []

        if issubclass(self.model, SectionBaseModel):
            section_fields = ["show_in_navigation", "section_name"]
        else:
            section_fields = []

        if issubclass(self.model, MarginBaseModel):
            margin_fields = ["margin_top", "margin_left", "margin_right", "margin_bottom"]
        else:
            margin_fields = []

        if issubclass(self.model, PaddingBaseModel):
            padding_fields = ["padding_top", "padding_left", "padding_right", "padding_bottom"]
        else:
            padding_fields = []

        fieldsets = super().get_fieldsets(request, obj)

        if section_fields:
            for field in section_fields:
                fieldsets[0][1]["fields"].remove(field)
            fieldsets.append(("Navigace na stránce", {"fields": section_fields, "classes": ["collapse"]}))

        if button_fields:
            for button_field in button_fields:
                fieldsets[0][1]["fields"].remove(button_field)
            fieldsets.append(("Tlačítko", {"fields": button_fields, "classes": ["collapse"]}))

        if margin_fields:
            for margin_field in margin_fields:
                fieldsets[0][1]["fields"].remove(margin_field)
            fieldsets.append(("Vnější odsazení", {"fields": margin_fields, "classes": ["collapse"]}))

        if padding_fields:
            for padding_field in padding_fields:
                fieldsets[0][1]["fields"].remove(padding_field)
            fieldsets.append(("Vnitřní odsazení", {"fields": padding_fields, "classes": ["collapse"]}))

        return fieldsets


class FooterSocialNetworkInline(admin.TabularInline, SortableInlineAdminMixin):
    """
    Sortable inline with social networks in footer
    """

    model = FooterSocialNetwork
    extra = 3


class FooterLinkInline(admin.TabularInline, SortableInlineAdminMixin):
    """
    Sortable inline with links in footer next to copyright text
    """

    model = FooterLink
    extra = 3
    fields = ["label", "open_in_new_window", "external_link", "internal_link"]


@plugin_pool.register_plugin
class FooterPlugin(NordicCMSPluginBase):
    """
    Footer plugin
    """

    module = "Patička"
    name = "Patička"
    render_template = "core/plugins/footer/footer.html"
    model = FooterPluginModel
    allow_children = True
    inlines = [FooterSocialNetworkInline, FooterLinkInline]
    child_classes = ["FooterColumnPlugin"]


class FooterColumnLinkInline(admin.TabularInline, SortableInlineAdminMixin):
    """
    Link in footer column
    """

    model = FooterColumnLink
    extra = 3
    fields = ["label", "open_in_new_window", "external_link", "internal_link"]


@plugin_pool.register_plugin
class FooterColumnPlugin(NordicCMSPluginBase):
    """
    Column inside footer plugin
    """

    module = "Patička"
    name = "Sloupec v patičce"
    render_template = "core/plugins/footer/footer_column.html"
    model = FooterColumnPluginModel
    inlines = [FooterColumnLinkInline]
    require_parent = True
    parent_classes = ["FooterPlugin"]

```

```
class NordicCMSPlugin(CMSPlugin):
    class Meta:
        abstract = True


class NordicCMSPluginBase(CMSPluginBase):
    """
    Base class for all plugins with some goodies
    """

    @property
    def name(self):
        raise NotImplementedError()

    def render(self, context, instance, placeholder) -> Dict:
        context = super().render(context, instance, placeholder) or {}
        context["plugin_name"] = self.name
        return context

    def get_fieldsets(self, request, obj=None):
        if issubclass(self.model, LinkIncludeOptionalButtonBaseModel):
            button_fields = ["label", "style", "open_in_new_window", "external_link", "internal_link"]
        elif issubclass(self.model, ButtonBaseModel):
            button_fields = ["label", "style"]
        else:
            button_fields = []

        if issubclass(self.model, SectionBaseModel):
            section_fields = ["show_in_navigation", "section_name"]
        else:
            section_fields = []

        if issubclass(self.model, MarginBaseModel):
            margin_fields = ["margin_top", "margin_left", "margin_right", "margin_bottom"]
        else:
            margin_fields = []

        if issubclass(self.model, PaddingBaseModel):
            padding_fields = ["padding_top", "padding_left", "padding_right", "padding_bottom"]
        else:
            padding_fields = []

        fieldsets = super().get_fieldsets(request, obj)

        if section_fields:
            for field in section_fields:
                fieldsets[0][1]["fields"].remove(field)
            fieldsets.append(("Navigace na stránce", {"fields": section_fields, "classes": ["collapse"]}))

        if button_fields:
            for button_field in button_fields:
                fieldsets[0][1]["fields"].remove(button_field)
            fieldsets.append(("Tlačítko", {"fields": button_fields, "classes": ["collapse"]}))

        if margin_fields:
            for margin_field in margin_fields:
                fieldsets[0][1]["fields"].remove(margin_field)
            fieldsets.append(("Vnější odsazení", {"fields": margin_fields, "classes": ["collapse"]}))

        if padding_fields:
            for padding_field in padding_fields:
                fieldsets[0][1]["fields"].remove(padding_field)
            fieldsets.append(("Vnitřní odsazení", {"fields": padding_fields, "classes": ["collapse"]}))

        return fieldsets
```

            
```
<div class="footer__navigation__column {% if instance.bold %}footer__navigation__column--main{% endif %}">
    <h3 class="footer__navigation__title">{{ instance.name_of_section }}</h3>
    <ul class="footer__navigation__menu">
        {% for item in instance.footercolumnlink_set.all %}
            <li class="footer__navigation__menu__item">
                <a class="footer__navigation__menu__link" href="{{ item.get_button_link }}"
                   {% if item.open_in_new_window %}target="_blank"{% endif %}>{{ item.label }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
```

## Steps to reproduce
1) Create such plugin in django-cms 4.1.1
2) Save it
3) Edit via doubleclick

## Expected behaviour

The error should not be thrown.

## Actual behaviour

It throws this error and the plugin can´t be edited.

## Screenshots

![image](https://github.com/django-cms/django-cms/assets/37733876/034ae5b0-20ed-4952-9cf6-0cd7d9e0424b)

## Additional information (CMS/Python/Django versions)

Whole stacktrace:
```
ERROR | 2024-06-12 16:39:52,516 | C:\Projects\nordic-web\venv\Lib\site-packages\django\utils\log.py:241 | log_response | Internal Server Error: /admin/cms/placeholder/edit-plugin/5/
Traceback (most recent call last):
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\views\decorators\clickjacking.py", line 58, in _view_wrapper
    response = view_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\cms\admin\placeholderadmin.py", line 600, in edit_plugin
    if not obj.placeholder.check_source(request.user):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\cms\models\placeholdermodel.py", line 209, in check_source
    return remote_field.run_checks(self, user)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PlaceholderField' object has no attribute 'run_checks'
```

requirements:
```
amqp==5.2.0 ; python_version >= "3.11" and python_version < "4.0"
asgiref==3.7.2 ; python_version >= "3.11" and python_version < "4.0"
attrs==23.2.0 ; python_version >= "3.11" and python_version < "4.0"
beautifulsoup4==4.12.3 ; python_version >= "3.11" and python_version < "4.0"
billiard==4.2.0 ; python_version >= "3.11" and python_version < "4.0"
camel-converter[pydantic]==3.1.1 ; python_version >= "3.11" and python_version < "4.0"
celery==5.3.6 ; python_version >= "3.11" and python_version < "4.0"
certifi==2024.2.2 ; python_version >= "3.11" and python_version < "4.0"
cffi==1.16 ; python_version >= "3.11" and python_version < "4.0"
charset-normalizer==3.3.2 ; python_version >= "3.11" and python_version < "4"
click-didyoumean==0.3.0 ; python_version >= "3.11" and python_version < "4.0"
click-plugins==1.1.1 ; python_version >= "3.11" and python_version < "4.0"
click-repl==0.3.0 ; python_version >= "3.11" and python_version < "4.0"
click==8.1.7 ; python_version >= "3.11" and python_version < "4.0"
colorama==0.4.6 ; python_version >= "3.11" and python_version < "4.0" and platform_system == "Windows"
cron-descriptor==1.2.35 ; python_version >= "3.11" and python_version < "4.0"
cryptography==42.0.5 ; python_version >= "3.11" and python_version < "4.0"
cssselect2==0.7.0 ; python_version >= "3.11" and python_version < "4.0"
django-admin-sortable2==2.1.10 ; python_version >= "3.11" and python_version < "4.0"
django-auto-logout==0.5.1 ; python_version >= "3.11" and python_version < "4.0"
django-celery-beat==2.6.0 ; python_version >= "3.11" and python_version < "4.0"
django-ckeditor==6.7.0 ; python_version >= "3.11" and python_version < "4.0"
django-dotenv===1.4.2; python_version >= "3.11" and python_version < "4.0"
django-classy-tags==4.1.0 ; python_version >= "3.11" and python_version < "4.0"
django-cms==4.1.1 ; python_version >= "3.11" and python_version < "4.0"
django-filer==3.1.3 ; python_version >= "3.11" and python_version < "4.0"
django-formtools==2.4.1 ; python_version >= "3.11" and python_version < "4.0"
django-js-asset==2.2.0 ; python_version >= "3.11" and python_version < "4.0"
django-meta==2.4.2 ; python_version >= "3.11" and python_version < "4.0"
django-mptt==0.14.0 ; python_version >= "3.11" and python_version < "4.0"
django-polymorphic==3.1.0 ; python_version >= "3.11" and python_version < "4.0"
django-sekizai==4.1.0 ; python_version >= "3.11" and python_version < "4.0"
django-solo==2.2.0 ; python_version >= "3.11" and python_version < "4.0"
django-timezone-field==5.0 ; python_version >= "3.11" and python_version < "4.0"
django-treebeard==4.7.0 ; python_version >= "3.11" and python_version < "4.0"
django-webpack-loader==3.0.1 ; python_version >= "3.11" and python_version < "4.0"
django-widget-tweaks==1.5.0 ; python_version >= "3.11" and python_version < "4.0"
django==5.0.0 ; python_version >= "3.11" and python_version < "4.0"
django-extensions==3.2.3 ; python_version >= "3.11" and python_version < "4.0"
djangocms-admin-style==3.3.0 ; python_version >= "3.11" and python_version < "4.0"
djangocms-text-ckeditor==5.1.5 ; python_version >= "3.11" and python_version < "4.0"
djangocms-versioning==2.0.1 ; python_version >= "3.11" and python_version < "4.0"
djangocms-alias==2.0.1 ; python_version >= "3.11" and python_version < "4.0"
djangocms-frontend==1.3.2 ; python_version >= "3.11" and python_version < "4.0"
django-fsm<3 ; python_version >= "3.11" and python_version < "4.0"
easy-thumbnails[svg]==2.8.5 ; python_version >= "3.11" and python_version < "4.0"
furl==2.1.3 ; python_version >= "3.11" and python_version < "4.0"
gunicorn==21.2.0 ; python_version >= "3.11" and python_version < "4.0"
html5lib==1.1 ; python_version >= "3.11" and python_version < "4.0"
idna==3.6 ; python_version >= "3.11" and python_version < "4"
isodate==0.6.1 ; python_version >= "3.11" and python_version < "4.0"
jwt==1.3.1 ; python_version >= "3.11" and python_version < "4.0"
kombu==5.3.5 ; python_version >= "3.11" and python_version < "4.0"
lxml==4.9.2 ; python_version >= "3.11" and python_version < "4.0"
meilisearch==0.31.0 ; python_version >= "3.11" and python_version < "4.0"
orderedmultidict==1.0.1 ; python_version >= "3.11" and python_version < "4.0"
packaging==24.0 ; python_version >= "3.11" and python_version < "4.0"
pillow==10.2.0 ; python_version >= "3.11" and python_version < "4.0"
platformdirs==4.1.0 ; python_version >= "3.11" and python_version < "4.0"
prompt-toolkit==3.0.43 ; python_version >= "3.11" and python_version < "4.0"
psycopg2-binary==2.9.9 ; python_version >= "3.11" and python_version < "4.0"
pycparser==2.21 ; python_version >= "3.11" and python_version < "4.0"
pycryptodome==3.20 ; python_version >= "3.11" and python_version < "4.0"
pydantic==2.6.4 ; python_version >= "3.11" and python_version < "4.0"
pyopenssl==24.1.0 ; python_version >= "3.11" and python_version < "4.0"
python-crontab==3.0.0 ; python_version >= "3.11" and python_version < "4.0"
python-dateutil==2.9.0 ; python_version >= "3.11" and python_version < "4.0"
pytz==2024.1 ; python_version >= "3.11" and python_version < "4.0"
redis==5.0.3 ; python_version >= "3.11" and python_version < "4.0"
reportlab==4.0 ; python_version >= "3.11" and python_version < "4"
requests-file==2.0.0 ; python_version >= "3.11" and python_version < "4.0"
requests-pkcs12==1.15 ; python_version >= "3.11" and python_version < "4.0"
requests-toolbelt==1.0.0 ; python_version >= "3.11" and python_version < "4.0"
requests==2.31.0 ; python_version >= "3.11" and python_version < "4"
sentry-sdk==1.17.0 ; python_version >= "3.11" and python_version < "4.0"
setuptools==69.2.0 ; python_version >= "3.11" and python_version < "4.0"
six==1.16.0 ; python_version >= "3.11" and python_version < "4.0"
soupsieve==2.5 ; python_version >= "3.11" and python_version < "4.0"
sqlparse==0.4.4 ; python_version >= "3.11" and python_version < "4.0"
svglib==1.5.1 ; python_version >= "3.11" and python_version < "4.0"
tinycss2==1.2.1 ; python_version >= "3.11" and python_version < "4.0"
typing-extensions==4.10.0 ; python_version >= "3.11" and python_version < "4.0"
tzdata==2024.1 ; python_version >= "3.11" and python_version < "4.0"
unidecode==1.3.8 ; python_version >= "3.11" and python_version < "4.0"
urllib3==1.26.18 ; python_version >= "3.11" and python_version < "4.0"
vine==5.1.0 ; python_version >= "3.11" and python_version < "4.0"
wcwidth==0.2.6 ; python_version >= "3.11" and python_version < "4.0"
webencodings==0.5.1 ; python_version >= "3.11" and python_version < "4.0"
xmltodict==0.13.0 ; python_version >= "3.11" and python_version < "4.0"
zeep==4.2.1 ; python_version >= "3.11" and python_version < "4.0"
fluent-logger==0.10.0 ; python_version >= "3.11" and python_version < "4.0"
django-prometheus==2.3.1 ; python_version >= "3.11" and python_version < "4.0"
```

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x] No, I only want to report the issue.

**Comment by marksweb** [comment]
Could you include `NordicCMSPluginBase` and `NordicCMSPlugin` please?

**Comment by zmara** [comment]
Added

**Comment by fsbraun** [comment]
@zmara What placeholder are you adding the plugin to? Is this a regular placeholder on a page or do you have custom models containing `PlaceholderField` entires?

**Comment by zmara** [comment]
I have no models where PlaceholderField is specified.

Also I get very similar error when I try to "Copy" my plugin in administration. And I get this error on every plugin, not just some of them.
`AttributeError: 'ForeignKey' object has no attribute 'run_checks'` - which is maybe more important issue for me.

**Comment by zmara** [comment]
I resolved it by replacing static_placeholder with static_alias (after upgrading to django-cms 4). But the copy issue remain, I will create new github issue.
