### ISSUE TITLE
[BUG] AttributeError: 'ForeignKey' object has no attribute 'run_checks'

### ISSUE THREAD

**Issue by zmara** [django-cms/django-cms#7937]
## Description
Copying any plugin throws this error: 'ForeignKey' object has no attribute 'run_checks' after upgrade to django-cms 4.

## Steps to reproduce
Hard to reproduce on new project, it is a legacy project updated to django-cms 4 recently.

## Expected behaviour
Copying should copy plugin without errors.

## Actual behaviour
Throwing error mentioned above.

## Additional information (CMS/Python/Django versions)
Whole stacktrace:
```
Traceback (most recent call last):
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\views\decorators\http.py", line 63, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\django\views\decorators\clickjacking.py", line 58, in _view_wrapper
    response = view_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maraz\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\cms\admin\placeholderadmin.py", line 436, in copy_plugins
    new_plugin = self._copy_plugin_to_clipboard(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\cms\admin\placeholderadmin.py", line 473, in _copy_plugin_to_clipboard
    if not target_placeholder.check_source(request.user):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\nordic-web\venv\Lib\site-packages\cms\models\placeholdermodel.py", line 209, in check_source
    return remote_field.run_checks(self, user)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ForeignKey' object has no attribute 'run_checks'
```

After debugging I can say, that remote_field is instance of Clipboard and you see it is happening during calling method _copy_plugin_to_clipboard.

This is my class User:
```
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    partner_id = models.CharField(default="", max_length=128, editable=False)
    partner_user_id = models.CharField(default="", max_length=128, editable=False)
```

requirements:
```
amqp==5.2.0 ; python_version >= "3.11" and python_version < "4.0"
asgiref==3.7.2 ; python_version >= "3.11" and python_version < "4.0"
attrs==23.2.0 ; python_version >= "3.11" and python_version < "4.0"
beautifulsoup4==4.12.3 ; python_version >= "3.11" and python_version < "4.0"
billiard==4.2.0 ; python_version >= "3.11" and python_version < "4.0"
camel-converter[pydantic]==3.1.1 ; python_version >= "3.11" and python_version < "4.0"
celery==5.3.6 ; python_version >= "3.11" and python_version < "4.0"
certifi==2024.2.2 ; python_version >= "3.11" and python_version < "4.0"
cffi==1.16 ; python_version >= "3.11" and python_version < "4.0"
charset-normalizer==3.3.2 ; python_version >= "3.11" and python_version < "4"
click-didyoumean==0.3.0 ; python_version >= "3.11" and python_version < "4.0"
click-plugins==1.1.1 ; python_version >= "3.11" and python_version < "4.0"
click-repl==0.3.0 ; python_version >= "3.11" and python_version < "4.0"
click==8.1.7 ; python_version >= "3.11" and python_version < "4.0"
colorama==0.4.6 ; python_version >= "3.11" and python_version < "4.0" and platform_system == "Windows"
cron-descriptor==1.2.35 ; python_version >= "3.11" and python_version < "4.0"
cryptography==42.0.5 ; python_version >= "3.11" and python_version < "4.0"
cssselect2==0.7.0 ; python_version >= "3.11" and python_version < "4.0"
django-admin-sortable2==2.1.10 ; python_version >= "3.11" and python_version < "4.0"
django-auto-logout==0.5.1 ; python_version >= "3.11" and python_version < "4.0"
django-celery-beat==2.6.0 ; python_version >= "3.11" and python_version < "4.0"
django-ckeditor==6.7.0 ; python_version >= "3.11" and python_version < "4.0"
django-dotenv===1.4.2; python_version >= "3.11" and python_version < "4.0"
django-classy-tags==4.1.0 ; python_version >= "3.11" and python_version < "4.0"
django-cms==4.1.1 ; python_version >= "3.11" and python_version < "4.0"
django-filer==3.1.3 ; python_version >= "3.11" and python_version < "4.0"
django-formtools==2.4.1 ; python_version >= "3.11" and python_version < "4.0"
django-js-asset==2.2.0 ; python_version >= "3.11" and python_version < "4.0"
django-meta==2.4.2 ; python_version >= "3.11" and python_version < "4.0"
django-mptt==0.14.0 ; python_version >= "3.11" and python_version < "4.0"
django-polymorphic==3.1.0 ; python_version >= "3.11" and python_version < "4.0"
django-sekizai==4.1.0 ; python_version >= "3.11" and python_version < "4.0"
django-solo==2.2.0 ; python_version >= "3.11" and python_version < "4.0"
django-timezone-field==5.0 ; python_version >= "3.11" and python_version < "4.0"
django-treebeard==4.7.0 ; python_version >= "3.11" and python_version < "4.0"
django-webpack-loader==3.0.1 ; python_version >= "3.11" and python_version < "4.0"
django-widget-tweaks==1.5.0 ; python_version >= "3.11" and python_version < "4.0"
django==5.0.0 ; python_version >= "3.11" and python_version < "4.0"
django-extensions==3.2.3 ; python_version >= "3.11" and python_version < "4.0"
djangocms-admin-style==3.3.0 ; python_version >= "3.11" and python_version < "4.0"
djangocms-text-ckeditor==5.1.5 ; python_version >= "3.11" and python_version < "4.0"
djangocms-versioning==2.0.1 ; python_version >= "3.11" and python_version < "4.0"
djangocms-alias==2.0.1 ; python_version >= "3.11" and python_version < "4.0"
djangocms-frontend==1.3.2 ; python_version >= "3.11" and python_version < "4.0"
django-fsm<3 ; python_version >= "3.11" and python_version < "4.0"
easy-thumbnails[svg]==2.8.5 ; python_version >= "3.11" and python_version < "4.0"
furl==2.1.3 ; python_version >= "3.11" and python_version < "4.0"
gunicorn==21.2.0 ; python_version >= "3.11" and python_version < "4.0"
html5lib==1.1 ; python_version >= "3.11" and python_version < "4.0"
idna==3.6 ; python_version >= "3.11" and python_version < "4"
isodate==0.6.1 ; python_version >= "3.11" and python_version < "4.0"
jwt==1.3.1 ; python_version >= "3.11" and python_version < "4.0"
kombu==5.3.5 ; python_version >= "3.11" and python_version < "4.0"
lxml==4.9.2 ; python_version >= "3.11" and python_version < "4.0"
meilisearch==0.31.0 ; python_version >= "3.11" and python_version < "4.0"
orderedmultidict==1.0.1 ; python_version >= "3.11" and python_version < "4.0"
packaging==24.0 ; python_version >= "3.11" and python_version < "4.0"
pillow==10.2.0 ; python_version >= "3.11" and python_version < "4.0"
platformdirs==4.1.0 ; python_version >= "3.11" and python_version < "4.0"
prompt-toolkit==3.0.43 ; python_version >= "3.11" and python_version < "4.0"
psycopg2-binary==2.9.9 ; python_version >= "3.11" and python_version < "4.0"
pycparser==2.21 ; python_version >= "3.11" and python_version < "4.0"
pycryptodome==3.20 ; python_version >= "3.11" and python_version < "4.0"
pydantic==2.6.4 ; python_version >= "3.11" and python_version < "4.0"
pyopenssl==24.1.0 ; python_version >= "3.11" and python_version < "4.0"
python-crontab==3.0.0 ; python_version >= "3.11" and python_version < "4.0"
python-dateutil==2.9.0 ; python_version >= "3.11" and python_version < "4.0"
pytz==2024.1 ; python_version >= "3.11" and python_version < "4.0"
redis==5.0.3 ; python_version >= "3.11" and python_version < "4.0"
reportlab==4.0 ; python_version >= "3.11" and python_version < "4"
requests-file==2.0.0 ; python_version >= "3.11" and python_version < "4.0"
requests-pkcs12==1.15 ; python_version >= "3.11" and python_version < "4.0"
requests-toolbelt==1.0.0 ; python_version >= "3.11" and python_version < "4.0"
requests==2.31.0 ; python_version >= "3.11" and python_version < "4"
sentry-sdk==1.17.0 ; python_version >= "3.11" and python_version < "4.0"
setuptools==69.2.0 ; python_version >= "3.11" and python_version < "4.0"
six==1.16.0 ; python_version >= "3.11" and python_version < "4.0"
soupsieve==2.5 ; python_version >= "3.11" and python_version < "4.0"
sqlparse==0.4.4 ; python_version >= "3.11" and python_version < "4.0"
svglib==1.5.1 ; python_version >= "3.11" and python_version < "4.0"
tinycss2==1.2.1 ; python_version >= "3.11" and python_version < "4.0"
typing-extensions==4.10.0 ; python_version >= "3.11" and python_version < "4.0"
tzdata==2024.1 ; python_version >= "3.11" and python_version < "4.0"
unidecode==1.3.8 ; python_version >= "3.11" and python_version < "4.0"
urllib3==1.26.18 ; python_version >= "3.11" and python_version < "4.0"
vine==5.1.0 ; python_version >= "3.11" and python_version < "4.0"
wcwidth==0.2.6 ; python_version >= "3.11" and python_version < "4.0"
webencodings==0.5.1 ; python_version >= "3.11" and python_version < "4.0"
xmltodict==0.13.0 ; python_version >= "3.11" and python_version < "4.0"
zeep==4.2.1 ; python_version >= "3.11" and python_version < "4.0"
fluent-logger==0.10.0 ; python_version >= "3.11" and python_version < "4.0"
django-prometheus==2.3.1 ; python_version >= "3.11" and python_version < "4.0"
```

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@zmara This is not related to a static placeholder. Can you confirm this happens when copying from a regular placeholder to another regular placeholder? I, so far, have failed to reproduce the issue.

**Comment by zmara** [comment]
This is not related to a static placeholder. A cannot copy any regular placeholder.
