### ISSUE TITLE
I tried to add a field to the user model, but it failed [BUG]

### ISSUE THREAD

**Issue by baloyou** [django-cms/django-cms#7957]
I'm using the version of djangocms 4.1, Am I missing something? Is there any documentation to do so? (I didn't find it...) ）

I want to add a field for the user with a mobile phone number, and I follow this step:

1. `python manage.py startapp users`
2.  ===============
```
INSTALLED_APPS = [
    ... # existing Django apps go here
    'users',
]
```
3. ===============
```
# users/models.py

from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    
    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'user'
        swappable = 'AUTH_USER_MODEL'

```
4. settings.py  `AUTH_USER_MODEL = 'users.User'`
5. `python manage.py makemigrations`

i got a error
```
Traceback (most recent call last):
  File "E:\python\code\django-cms\www\manage.py", line 22, in <module>
    main()
  File "E:\python\code\django-cms\www\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "E:\python\code\django-cms\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "E:\python\code\django-cms\.venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "E:\python\code\django-cms\.venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\python\code\django-cms\.venv\Lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "E:\python\code\django-cms\.venv\Lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\python\code\django-cms\.venv\Lib\site-packages\cms\models\__init__.py", line 5, in <module>
    from .permissionmodels import *  # nopyflakes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\code\django-cms\.venv\Lib\site-packages\cms\models\permissionmodels.py", line 20, in <module>
    User = apps.get_registered_model(user_app_name, user_model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\code\django-cms\.venv\Lib\site-packages\django\apps\registry.py", line 280, in get_registered_model
    raise LookupError("Model '%s.%s' not registered." % (app_label, model_name))
LookupError: Model 'users.User' not registered.
```

**Comment by baloyou** [comment]
After I added this line of code to the models.py, it seemed to work (preferably before the first data migration)

```
    def __str__(self):
        return self.username
```

**Comment by fsbraun** [comment]
Hi @baloyou ! Great, that it seems to work. Maybe, also look at this Post... https://discord.com/channels/800813886689247262/1246874875650642032/1247125905093165086

**Comment by fsbraun** [comment]
@baloyou Can we close this?
