### ISSUE TITLE
[BUG]3.11.8 version has cms:permissions error 'keyerror'

### ISSUE THREAD

**Issue by svandeneertwegh** [django-cms/django-cms#8020]
Installed 3.11.8 latest but got this error..
When i revert back to 311.6 it works again.

stacktrace:
----------------------------------------------

System check identified no issues (0 silenced).
October 03, 2024 - 21:27:48
Django version 4.2.13, using settings 'config.settings.local'
Starting development server at http://localhost:8000/
Quit the server with CONTROL-C.

/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/cms_toolbars.py:122: UserWarning: This API function will be removed in django CMS 4. For publishing functionality use a package that adds publishing, such as: djangocms-versioning.
  self.page = get_page_draft(self.request.current_page)
/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/utils/page_permissions.py:284: UserWarning: This API function will be removed in django CMS 4. For publishing functionality use a package that adds publishing, such as: djangocms-versioning.
  page = get_page_draft(page)
/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/cms_toolbars.py:67: UserWarning: This API function will be removed in django CMS 4. For publishing functionality use a package that adds publishing, such as: djangocms-versioning.
  self.page = get_page_draft(self.request.current_page)
/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/cms_toolbars.py:396: UserWarning: This API function will be removed in django CMS 4. For publishing functionality use a package that adds publishing, such as: djangocms-versioning.
  self.page = get_page_draft(self.request.current_page)
/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/djangocms_page_sitemap/cms_toolbars.py:20: UserWarning: This API function will be removed in django CMS 4. For publishing functionality use a package that adds publishing, such as: djangocms-versioning.
  self.page = get_page_draft(self.request.current_page)
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/classytags/core.py", line 142, in render
    return str(self.render_tag(context, **kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/sekizai/templatetags/sekizai_tags.py", line 87, in render_tag
    rendered_contents = nodelist.render(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/classytags/core.py", line 142, in render
    return str(self.render_tag(context, **kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/templatetags/cms_tags.py", line 434, in render_tag
    return toolbar.render_with_structure(context, nodelist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/toolbar/toolbar.py", line 466, in render_with_structure
    self.populate()
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/toolbar/toolbar.py", line 405, in populate
    self._call_toolbar('populate')
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/toolbar/toolbar.py", line 432, in _call_toolbar
    getattr(toolbar, func_name)()
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/djangocms_page_sitemap/cms_toolbars.py", line 29, in populate
    has_global_current_page_change_permission = has_page_permission(
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/utils/permissions.py", line 196, in has_page_permission
    return has_generic_permission(page, user, action, site=None, check_global=False, use_cache=use_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stefan/.pyenv/versions/eertwegh-tech/lib/python3.11/site-packages/cms/utils/page_permissions.py", line 508, in has_generic_permission
    func = actions_map[action]
           ~~~~~~~~~~~^^^^^^^^
KeyError: 'change'

**Comment by fsbraun** [comment]
@svandeneertwegh There's a fix coming up (#8022). Also, this should be solved by installing https://github.com/fsbraun/djangocms-page-sitemap/tree/patch-1 from https://github.com/nephila/djangocms-page-sitemap/pull/120. Can you give https://github.com/nephila/djangocms-page-sitemap/pull/120 a test run?
