### ISSUE TITLE
[BUG] Migration fails when adding django-cms to existing project

### ISSUE THREAD

**Issue by JanSchmidPD** [django-cms/django-cms#8082]
## Description

I followed the documentation at https://docs.django-cms.org/en/latest/introduction/01-install.html#adding-django-cms-to-an-existing-django-project and followed it to the step "Database tables" where the migration 0002_auto_20140816_1918.py fails with `LookupError: App 'cms' doesn't have a 'title' model.`

I suspect the error comes from line 113 of 0002_auto_20140816_1918.py, specificaly the `migrations.CreateModel(name='Title',`:

In cms/model i cannot find any model named Title. After looking through older releases and the migration files, it looks like the "Title" model was renamed to "PageContent".

The old migrationfile 0002 still want to create the "Title" model to rename it later in file 0032.

## Steps to reproduce
follow the documentation at https://docs.django-cms.org/en/latest/introduction/01-install.html#adding-django-cms-to-an-existing-django-project

## Expected behaviour
migration succeeds 

## Actual behaviour
Migration fails with Lookuperror. Full stacktrace:
```Traceback (most recent call last):
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\apps\config.py", line 235, in get_model
    return self.models[model_name.lower()]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SCJA\Documents\git\webgui\PDM\webGui\manage.py", line 22, in <module>
    main()
  File "C:\Users\SCJA\Documents\git\webgui\PDM\webGui\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\core\management\commands\migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\migrations\executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\migrations\executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\migrations\executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\migrations\migration.py", line 132, in apply
    operation.database_forwards(
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\migrations\operations\models.py", line 95, in database_forwards
    if self.allow_migrate_model(schema_editor.connection.alias, model):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\migrations\operations\base.py", line 127, in allow_migrate_model
    return router.allow_migrate_model(connection_alias, model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\utils.py", line 268, in allow_migrate_model
    return self.allow_migrate(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\db\utils.py", line 261, in allow_migrate
    allow = method(db, app_label, **hints)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\PDM\webGui\dbRouter\DatabaseRouter.py", line 85, in allow_migrate
    model = apps.get_model(app_label=app_label, model_name=model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\apps\registry.py", line 213, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\apps\config.py", line 237, in get_model
    raise LookupError(
LookupError: App 'cms' doesn't have a 'title' model.
```

## Additional information (CMS/Python/Django versions)
Django==5.0.6
django-cms==4.1.4

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@JanSchmidPD I cannot reproduce the issue. Actually, the very migration you name creates the `Title` model. What are your migration settings?

**Comment by marksweb** [comment]
> I suspect the error comes from line 113 of 0002_auto_20140816_1918.py, specificaly the `migrations.CreateModel(name='Title',`:

> In cms/model i cannot find any model named Title. After looking through older releases and the migration files, it looks like the "Title" model was renamed to "PageContent".
> 
> The old migrationfile 0002 still want to create the "Title" model to rename it later in file 0032.

If you've not got any CMS tables yet, then yes, this migration will try to create a `Title` table. But that wouldn't error at that point by default. It should apply all migrations and by the time migrations complete you don't have a `Title` table anymore, but a `PageContent` one because you're using django-cms 4.

> Migration fails with Lookuperror. Full stacktrace:
> 
> ```
>   File "C:\Users\SCJA\Documents\git\webgui\venv\Lib\site-packages\django\apps\config.py", line 235, in get_model
>     return self.models[model_name.lower()]
>            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
> KeyError: 'title'
> 
>   File "C:\Users\SCJA\Documents\git\webgui\PDM\webGui\dbRouter\DatabaseRouter.py", line 85, in allow_migrate
>     model = apps.get_model(app_label=app_label, model_name=model_name)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\SCJA\Documents\git\webgui\PDM\webGui\dbRouter\DatabaseRouter.py", line 85, in allow_migrate
>     model = apps.get_model(app_label=app_label, model_name=model_name)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

I'm curious what you've got in your database router if Fabian can't replicate this and you've got an `allow_migration` method. Maybe that's trying to load the model and it doesn't exist?

**Comment by JanSchmidPD** [comment]
@marksweb Im quite new to django migrations, sadly I wasn't aware of it for a long time when starting my project. 
You are right i do have a dbrouter that defines a allow_migrate: 
`
    def allow_migrate(self, db, app_label, model_name=None, **hints):
        """
        Make sure that each non-default db table only appear in the 
        corresponding database.
        """
        if model_name is not None:
            model = apps.get_model(app_label=app_label, model_name=model_name)
            for dbMap in self.tableMap:
                if model._meta.db_table in self.tableMap[dbMap]:
                    return db == dbMap
        if db == 'default':
            return True
        return False
`
For me the migrations only ever worked if the name in CreateModel was already defined in models.py. Which didnt make sense to me but was my only workaround. So i guess my allow_migration is wrong?
